# Generated by Django 5.0.4 on 2024-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(help_text='Shorthand days of the week that the rate applies to', max_length=32)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.PositiveIntegerField(help_text='Prices in format 0000 in US Dollars')),
            ],
        ),
    ]
