# Generated by Django 5.0.4 on 2024-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrate',
            name='original_given_timezone',
            field=models.CharField(default=0, help_text='Timezone specified by owner', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingrate',
            name='original_time_range',
            field=models.CharField(default=0, help_text='Original time range provided before conversion to UTC', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='end_time',
            field=models.TimeField(help_text='All times stored as UTC'),
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='start_time',
            field=models.TimeField(help_text='All times stored as UTC'),
        ),
    ]
