# Generated by Django 5.0.4 on 2024-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_parkingrate_original_given_timezone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingrate',
            old_name='end_time',
            new_name='end_time_utc',
        ),
        migrations.RenameField(
            model_name='parkingrate',
            old_name='start_time',
            new_name='start_time_utc',
        ),
        migrations.AddField(
            model_name='parkingrate',
            name='end_time_original',
            field=models.TimeField(default='01:00', help_text='All times stored as the given tz upon ingestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingrate',
            name='start_time_original',
            field=models.TimeField(default='01:00', help_text='All times stored as the given tz upon ingestion'),
            preserve_default=False,
        ),
    ]
