# Generated by Django 5.0.4 on 2024-04-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_rename_end_time_parkingrate_end_time_utc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingrate',
            name='days',
            field=models.CharField(db_index=True, help_text='Shorthand days of the week that the rate applies to', max_length=32),
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='end_time_utc',
            field=models.TimeField(db_index=True, help_text='All times stored as UTC'),
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='start_time_utc',
            field=models.TimeField(db_index=True, help_text='All times stored as UTC'),
        ),
    ]
